name: Docker Build Check

on:
  push:
    branches:
      - "feature/**"

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set branch tag
        run: |
          IMAGE_TAG=$(echo "${GITHUB_REF_NAME}" | tr '/' '-')
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "Using image tag: ${IMAGE_TAG}"

      - name: Build Docker image
        run: |
          IMAGE_NAME="discord_bot"
          echo "Building ${IMAGE_NAME}:${IMAGE_TAG}"

          docker build \
            -t ${IMAGE_NAME}:${IMAGE_TAG} \
            .
