name: Docker Build Check

on:
  push:
    branches:
      - "feature/**"

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set branch tag
        run: echo "IMAGE_TAG=$(echo ${GITHUB_REF_NAME} | tr '/' '-')" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build --pull -t discord_bot:${IMAGE_TAG} .
